server:
  port: 8089  # 서버 포트 번호 설정

spring:
  datasource:
    url: jdbc:mysql://localhost:3308/mes_db # MySQL 접속 URL, 타임존 설정 포함
    username: root  # DB 접속 사용자명
    password: rootpassword  # DB 접속 비밀번호
    driver-class-name: com.mysql.cj.jdbc.Driver  # MySQL 드라이버 클래스명

mybatis:
  mapper-locations: classpath:mapper/**/*.xml  # 매퍼 XML 파일 위치 패턴
  type-aliases-package: com.ohyungsang.mes.domain  # 도메인(엔티티) 클래스 패키지 지정 (별칭 등록)
  type-handlers-package: com.ohyungsang.mes.config.typehandler
  configuration:
    default-statement-timeout: 30  # 쿼리 실행 기본 타임아웃(초)
    map-underscore-to-camel-case: true  # DB 컬럼 스네이크 표기법을 카멜 표기법으로 자동 변환
    jdbc-type-for-null: varchar  # null 값 처리 시 기본 JDBC 타입 지정 (VARCHAR로 설정)
    call-setters-on-nulls: true  # null 값일 때도 setter 호출하여 명확히 null 처리
    auto-mapping-unknown-column-behavior: none  # 매핑되지 않은 컬럼 발생 시 아무 동작 안 함 (예외 발생 안 함)

