jwt:
  secretKey: ${JWT_SECRET_KEY:awfweoafjaweofnmawsweafaweffewfaeklfniowehfioweaowieaf}
  access:
    expiration: 1800000
    header: Authorization
  refresh:
    expiration: 1209600000
    header: Authorization-refresh