server:
  servlet:
    encoding:
      force-response: true
  port: 8081
spring:
  profiles:
    include:
      - s3
      - redis
      - jwt
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: oracle
    database-platform: org.hibernate.dialect.Oracle12cDialect


logging:
  level:
    org.hibernate.SQL: debug    # Logger
    org.hibernate.type: trace   # Show Query Parameter
