name: FrontEnd CI PipeLine

# Workflow를 실행시키기 위한 Event 목록
on:
  pull_request:
    branches:
      - main
    paths:
      - 'frontend/**'

  # 해당 옵션을 통해 사용자가 직접 Actions 탭에서 Workflow를 실행시킬 수 있음
  workflow_dispatch:

defaults:
  run:
    working-directory: ./frontend
    
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run:
          aws s3 sync . s3://mymesproject --delete

#      # CloudFront 적용하면 넣기
#      - name: Invalidate CloudFront Cache
#        run: aws cloudfront create-invalidation --distribution-id ${{secrets.DEV_AWS_DISTRIBUTION_ID}} --paths "/*"    
    

# jobs:
#   build:
#     runs-on: ubuntu-18.04
#     steps:
#       - name: Checkout source code.   # 레포지토리 체크아웃
#         uses: actions/checkout@master

#       - name: Cache node modules      # node modules 캐싱
#         uses: actions/cache@v1
#         with:
#           path: node_modules
#           key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
#           restore-keys: |
#             ${{ runner.OS }}-build-
#             ${{ runner.OS }}-

#       - name: Install Dependencies    # 의존 파일 설치
#         run: npm install

#       - name: Build                   # React Build
#         run: npm run build

#       - name: Deploy                  # S3에 배포하기
#         env:
#           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#         run: |
#           aws s3 cp \
#             --recursive \
#             --region ap-northeast-2 \
#             build s3://github-action-tutorial # 자신의 레포지토리로 변경해주세요.
